Repository HIYOCOch/practice_github_actions, pull requests merged in 2020-04, with the labels that each got.

#1 1st commit
  .github/workflows/main.yml
  hello.py
Labels: release:major

#2 2nd commit
  hello.py
Labels: release:major

#3 3rd commit
  hello.py
Labels: release:minor

#7 ActionsTest4
  hello.py
Labels: release:major

#8 ActionsTest5
  hello.py
Labels: release:minor

#9 ActionsTest6
  hello.py
Labels: release:minor

#10 ActionsTest7
  hello.py
Labels: release:minor

#11 ActionsTest8
  hello.py
Labels: release:patch

#12 ActionsTest9
  hello.py
Labels: release:major

#13 ActionsTest10
  hello.py
Labels: release:minor

#14 ActionsTest11
  hello.py
Labels: release:patch

#15 ActionsTest12
  hello.py
Labels: release:minor

#16 ActionsTest13
  hello.py
Labels: release:minor

#17 ActionsTest14
  hello.py
Labels: release:patch

#18 ActionsTest15
  hello.py
Labels: release:major

#19 ActionsTest16
  hello.py
Labels: release:major

#20 ActionsTest17
  hello.py
Labels: release:minor

#21 ActionsTest18
  hello.py
Labels: release:major
